//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentinelsOfTheMultiverse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_jp_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_jp_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentinelsOfTheMultiverse.Properties.Resources.jp-JP", typeof(Resources_jp_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終えた.
        /// </summary>
        internal static string EndTurn {
            get {
                return ResourceManager.GetString("EndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハカ.
        /// </summary>
        internal static string Haka {
            get {
                return ResourceManager.GetString("Haka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦いのハカ.
        /// </summary>
        internal static string HakaOfBattle {
            get {
                return ResourceManager.GetString("HakaOfBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2枚のカードを引く。捨てる少なくとも1カード。廃棄された各カードに1ずつハカで配ら次のダメージを増加させる。.
        /// </summary>
        internal static string HakaOfBattleEffect {
            get {
                return ResourceManager.GetString("HakaOfBattleEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大暴れ.
        /// </summary>
        internal static string Rampage {
            get {
                return ResourceManager.GetString("Rampage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハカは各非ヒーロー5メレーダメージを与える。ハカは、各ヒーロー2メレーダメージを与える。.
        /// </summary>
        internal static string RampageEffect {
            get {
                return ResourceManager.GetString("RampageEffect", resourceCulture);
            }
        }
    }
}
